# Generated by Django 4.0.1 on 2022-01-17 07:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=10)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('semster', models.IntegerField(blank=True)),
                ('hostel_or_Home', models.CharField(blank=True, max_length=20)),
                ('hostel_number', models.PositiveIntegerField(blank=True, default=None)),
                ('native_language', models.CharField(default=None, max_length=10)),
                ('languages_known', models.CharField(default=None, max_length=100)),
                ('hoddies', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, default=None)),
                ('state', models.CharField(default=None, max_length=40)),
                ('country', models.CharField(default='India', max_length=20)),
                ('instagram', models.CharField(blank=True, default=None, max_length=100)),
                ('gmail', models.EmailField(blank=True, max_length=100)),
                ('linkdin', models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=100)),
                ('whatsapp', models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
